import AddOnsBlock from "./AddOnsBlock";
import BrochureLayout from "./BrochureLayout";
import ContactBlock from "./ContactBlock";

export default function BrochureSocieties() {
  return (
    <BrochureLayout orgType="Societies and Residential">
      <section className="mb-5">
        <p className="text-base text-gray-700 leading-relaxed">
          Ecowaste Management Solutions will provide comprehensive, eco-friendly
          waste management products and cleaning services to institutions across
          India. We will build complete waste management systems -- not just
          supply products.
        </p>
      </section>

      <section className="mb-5">
        <h2 className="text-xl font-bold text-green-800 border-l-4 border-green-600 pl-3 mb-3">
          Key Statistics
        </h2>
        <div className="grid grid-cols-2 gap-4">
          <div className="bg-yellow-50 border border-yellow-200 rounded-lg p-4">
            <div className="text-3xl font-extrabold text-yellow-700">
              100,000T
            </div>
            <div className="text-sm text-gray-600">
              tonnes of waste generated by India's urban households daily
            </div>
          </div>
          <div className="bg-orange-50 border border-orange-200 rounded-lg p-4">
            <div className="text-3xl font-extrabold text-orange-600">
              Only 43%
            </div>
            <div className="text-sm text-gray-600">
              of waste collected in urban areas, leaving a massive collection
              gap
            </div>
          </div>
        </div>
      </section>

      <div className="grid grid-cols-2 gap-8 mb-5">
        <section>
          <h2 className="text-base font-bold text-green-800 mb-2">
            Waste Challenges in Societies
          </h2>
          <ul className="space-y-2">
            {[
              "Mixed waste disposal with no segregation",
              "No composting setup for organic waste",
              "Poor common area hygiene and overflowing bins",
              "Low resident participation and awareness",
            ].map((c) => (
              <li
                key={c}
                className="flex items-start gap-2 text-base text-gray-700"
              >
                <span className="mt-1.5 w-2 h-2 rounded-full bg-red-400 flex-shrink-0" />
                {c}
              </li>
            ))}
          </ul>
        </section>
        <section>
          <h2 className="text-base font-bold text-green-800 mb-2">
            What We Will Provide
          </h2>
          <ul className="space-y-2">
            {[
              "Colour-coded bins for all common areas",
              "Composting setup for organic waste",
              "Floor-wise collection planning",
              "Resident guidance and awareness sessions",
              "Waste storage area setup",
            ].map((p) => (
              <li
                key={p}
                className="flex items-start gap-2 text-base text-gray-700"
              >
                <span className="mt-1.5 w-2 h-2 rounded-full bg-green-500 flex-shrink-0" />
                {p}
              </li>
            ))}
          </ul>
        </section>
      </div>

      <section className="mb-4">
        <h2 className="text-xl font-bold text-green-800 border-l-4 border-green-600 pl-3 mb-3">
          Recommended Packages
        </h2>
        <div className="grid grid-cols-2 gap-4">
          <div className="bg-green-50 border border-green-200 rounded-lg p-5">
            <div className="flex items-center justify-between mb-2">
              <span className="font-bold text-green-800 text-base">
                Basic Package
              </span>
              <span className="bg-green-700 text-white text-xs font-semibold px-2 py-0.5 rounded-full">
                Rs. 25K -- 75K
              </span>
            </div>
            <p className="text-sm text-gray-600">
              For smaller housing societies with basic segregation needs.
            </p>
          </div>
          <div className="bg-blue-50 border border-blue-200 rounded-lg p-5">
            <div className="flex items-center justify-between mb-2">
              <span className="font-bold text-blue-800 text-base">
                Standard Package
              </span>
              <span className="bg-blue-700 text-white text-xs font-semibold px-2 py-0.5 rounded-full">
                Rs. 75K -- 2.5L
              </span>
            </div>
            <p className="text-sm text-gray-600">
              For larger residential complexes needing comprehensive setup and
              training.
            </p>
          </div>
        </div>
      </section>

      <AddOnsBlock />

      <div className="my-4 bg-yellow-600 text-white rounded-lg p-4 text-center">
        <p className="font-semibold text-base italic">
          "A clean society starts with the right system. We will build it for
          you."
        </p>
      </div>

      <ContactBlock />
    </BrochureLayout>
  );
}
