/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const OrganizationType = IDL.Variant({
  'hospital' : IDL.Null,
  'other' : IDL.Text,
  'school' : IDL.Null,
  'civilSociety' : IDL.Null,
});
export const ServiceType = IDL.Variant({
  'wasteCollection' : IDL.Null,
  'cleaning' : IDL.Null,
  'other' : IDL.Text,
  'consulting' : IDL.Null,
  'products' : IDL.Null,
});
export const Time = IDL.Int;
export const QuoteRequest = IDL.Record({
  'organizationName' : IDL.Text,
  'organizationType' : OrganizationType,
  'serviceType' : ServiceType,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
});

export const idlService = IDL.Service({
  'getAllQuoteRequests' : IDL.Func([], [IDL.Vec(QuoteRequest)], ['query']),
  'submitQuoteRequest' : IDL.Func(
      [IDL.Text, IDL.Text, OrganizationType, ServiceType, IDL.Text, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const OrganizationType = IDL.Variant({
    'hospital' : IDL.Null,
    'other' : IDL.Text,
    'school' : IDL.Null,
    'civilSociety' : IDL.Null,
  });
  const ServiceType = IDL.Variant({
    'wasteCollection' : IDL.Null,
    'cleaning' : IDL.Null,
    'other' : IDL.Text,
    'consulting' : IDL.Null,
    'products' : IDL.Null,
  });
  const Time = IDL.Int;
  const QuoteRequest = IDL.Record({
    'organizationName' : IDL.Text,
    'organizationType' : OrganizationType,
    'serviceType' : ServiceType,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
  });
  
  return IDL.Service({
    'getAllQuoteRequests' : IDL.Func([], [IDL.Vec(QuoteRequest)], ['query']),
    'submitQuoteRequest' : IDL.Func(
        [IDL.Text, IDL.Text, OrganizationType, ServiceType, IDL.Text, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };