/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type OrganizationType = { 'hospital' : null } |
  { 'other' : string } |
  { 'school' : null } |
  { 'civilSociety' : null };
export interface QuoteRequest {
  'organizationName' : string,
  'organizationType' : OrganizationType,
  'serviceType' : ServiceType,
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : Time,
}
export type ServiceType = { 'wasteCollection' : null } |
  { 'cleaning' : null } |
  { 'other' : string } |
  { 'consulting' : null } |
  { 'products' : null };
export type Time = bigint;
export interface _SERVICE {
  'getAllQuoteRequests' : ActorMethod<[], Array<QuoteRequest>>,
  'submitQuoteRequest' : ActorMethod<
    [string, string, OrganizationType, ServiceType, string, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];